// Copyright 2014 the V8 project authors. All rights reserved.
// AUTO-GENERATED BY tools/generate-runtime-tests.py, DO NOT MODIFY
// Flags: --allow-natives-syntax --harmony --simd-object
var _self = SIMD.float64x2(0.0, 0.0);
var _lo = SIMD.float64x2(0.0, 0.0);
var _hi = SIMD.float64x2(0.0, 0.0);
%Float64x2Clamp(_self, _lo, _hi);
